CREATE TABLE BOARDS (
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BOARDS_NAME (NAME)
);

CREATE TABLE SWIMLANES (
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    SORT_ORDER SMALLINT NOT NULL,
    BOARD_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SWIMLANES_ID__BOARD_ID (ID, BOARD_ID)
);

ALTER TABLE SWIMLANES ADD FOREIGN KEY (BOARD_ID) REFERENCES BOARDS (ID);