CREATE TABLE BOARDS (
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BOARDS_NAME (NAME)
);

CREATE TABLE SWIMLANES (
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BOARD_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SWIMLANES_ID__BOARD_ID (ID, BOARD_ID)
);

ALTER TABLE SWIMLANES ADD FOREIGN KEY (BOARD_ID) REFERENCES BOARDS (ID);

CREATE TABLE TASKS (
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    TARGET_DATE TIMESTAMP,
    STATUS VARCHAR(16) NOT NULL,
    SWIMLANE_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TASKS_ID__SWIMLANE_ID (ID, STATUS, SWIMLANE_ID)
);

ALTER TABLE TASKS ADD FOREIGN KEY (SWIMLANE_ID) REFERENCES SWIMLANES(ID);